# GoReleaser configuration for TTS Lifeboat
# https://goreleaser.com

version: 2

project_name: lifeboat

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: ./cmd/lifeboat
    binary: lifeboat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/kannan/tts-lifeboat/internal/app.Version={{.Version}}
      - -X github.com/kannan/tts-lifeboat/internal/app.Commit={{.Commit}}
      - -X github.com/kannan/tts-lifeboat/internal/app.Date={{.Date}}
      - -X github.com/kannan/tts-lifeboat/internal/app.Creator=Kannan
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - MANUAL.md
      - LICENSE*
      - configs/lifeboat.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: krisk248
    name: tts-lifeboat
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## TTS Lifeboat v{{.Version}}

    Enterprise backup solution for Tomcat web applications.

    Created by Kannan
  footer: |
    ---

    *"In case of sinking Tomcat, grab the Lifeboat!"*
